# conda environment description file for ECget package
# development environment

name: ecget

channels:
  - conda-forge
  - defaults

dependencies:
  - beautifulsoup4
  - pip
  - python=3.6
  - requests

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  # For exploration
  - ipython
  - jupyter

  - pip:
    - arrow
    - cliff
    - kombu

    # For coding style
    - yapf
